### ISSUE TITLE
Failed to rebuild some binaries to match with Electron version

### ISSUE THREAD

**Issue by kurtern84** [eouia/MMM-Hotword#1]
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.11.3 | linux | arm
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, unlink 'build/config.gypi'
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/usr/local/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/.bin/node-gyp" "rebuild" "--target=2.0.0" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm" "--remote_path=./snowboy/v1.3.1/Release/" "--package_name=snowboy-v1.3.1-electron-v2.0-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.7.0
gyp info using node@8.11.3 | linux | arm
gyp ERR! clean error
gyp ERR! stack Error: EACCES: permission denied, unlink 'build/config.gypi'
gyp ERR! System Linux 4.14.52-v7+
gyp ERR! command "/usr/local/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/.bin/node-gyp" "rebuild" "--target=2.0.0" "--arch=arm" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm" "--remote_path=./snowboy/v1.3.1/Release/" "--package_name=snowboy-v1.3.1-electron-v2.0-linux-arm.tar.gz" "--host=https://snowboy-release-node.s3-us-west-2.amazonaws.com"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/rxjs/Subscriber.js:201:26)
    at Subscriber._error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/rxjs/Subscriber.js:132:26)
    at Subscriber.error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/rxjs/Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/rxjs/Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/rxjs/Subscriber.js:106:18)
    at SafeSubscriber._next (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.next (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/rxjs/Subscriber.js:189:22)

**Comment by eouia** [comment]
For making things simple, 
Your prior installation was a success? Have you tested this in `serveronly` mode?
Anyway, I'm preparing a new RPI for testing it. It'll take a few hours.

**Comment by kurtern84** [comment]
Yes, no problem there. Tried that also but no luck there either.

OK, sounds good😊

**Comment by eouia** [comment]
I've found my README.md had some miss.
Try this.
```shell
cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm install --save-dev electron-rebuild
npm install nan
./node_modules/.bin/electron-rebuild   # It could takes dozens sec.
```

**Comment by kurtern84** [comment]
Thanks, works fine now. 👍

**Comment by eouia** [comment]
Nice. I'll close this issue. Thanks for your interests.
