### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by PiggiCZ** [eouia/MMM-Hotword#102]
**Hello,**

I'm having trouble to get this module working and I don't understand the problems so I though you could help me.

This is what it tells me inside the console after running: sudo npm start

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-linux-arm-glibc
Found: [node-v64-linux-arm-glibc]

This problem can often be fixed by running **"npm rebuild"** on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
App threw an error during load
Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-linux-arm-glibc
Found: [node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node'
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:64:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12)
Whoops! There was an uncaught exception...
{ Error: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: electron-v3.0-linux-arm-glibc
Found: [node-v64-linux-arm-glibc]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/node/extension_binary/electron-v3.0-linux-arm-glibc/grpc_node.node'
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:53:17)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/grpc_extension.js:64:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:144:12) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

If I try the **sudo npm rebuild** it completes but nothing change after sudo npm start.

**This is my config.js file:**

{
    module: "MMM-AssistantMk2",
    position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },
{
  module: "MMM-Hotword",
  position: "top_right",
  config: {
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:1"
    },
    models: [
      {
        hotwords    : "computer",
        file        : "computer.umdl",
        sensitivity : "0.5",
      },
    ],
    commands: {
      "computer": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: (detected, afterRecord) => {
            return {profile:"default"}
          }
        },
        restart:false,
        afterRecordLimit:0
      }
    }
  }
},

**If I get rid of the MMM-Hotword module it works normally as it should**

I'm lost in loop and don't know how to finish my project.

Would be thankfull for any advice.

**Comment by eouia** [comment]
1. Your error message is shown your `electron-rebuild` fails on installation of `MMM-AssistantMk2`.
2. You've duplicated `MMM-Hotword` configuration.

**Comment by PiggiCZ** [comment]
1. will try new electron rebuild
2. I have deleted the duplicate

**Comment by PiggiCZ** [comment]
So I followed these instructions:

cd MMM-AssistantMk2
npm install
cd scripts
chmod +x *.sh
cd ~/MagicMirror/modules/MMM-AssistantMk2
npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild

Made succesfull rebuild but still same result:

> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module './snowboy/lib/node/index.js'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
App threw an error during load
Error: Cannot find module './snowboy/lib/node/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:244:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module './snowboy/lib/node/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:244:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

**Comment by PiggiCZ** [comment]
going to remove the folder MMM-AssistantMk2 and do it from the scrap

**Comment by eouia** [comment]
Well, in this case, the log says MMM-Hotword installation fails also. (Not MMM-AssistantMk2)

**Comment by PiggiCZ** [comment]
Ok, thanks a lot, will rebuild the MMM-Hotword too

**Comment by PiggiCZ** [comment]
This time I have followed these instructions and the rebuild was done in less than 2 secs. Could there be a problem with that? or is it suppose to be that quick ?

cd MMM-Hotword
npm install

cd ~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm install --save-dev electron-rebuild
npm install nan
./node_modules/.bin/electron-rebuild

**Comment by PiggiCZ** [comment]
> magicmirror@2.9.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module './snowboy/lib/node/index.js'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-NowPlayingOnSpotify
Initializing new module helper ...
Module helper loaded: calendar
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
App threw an error during load
Error: Cannot find module './snowboy/lib/node/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:244:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module './snowboy/lib/node/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:244:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

**Comment by eouia** [comment]
I don't know where you got the instruction which is used for your last installation.

Follow this;
https://github.com/eouia/MMM-Hotword/blob/master/documents/install.md

**Comment by PiggiCZ** [comment]
This is very awkward question, but how do I trigger the mirror ? Everything seems to be working but I don't know hot to speak with it

**Comment by eouia** [comment]
Trigger the mirror???

If you meant MMM-AssistantMk2, it needs awakener(activator). Any module which can emit proper notification could be the activator. e.g: H/W buttons, sensors, detectors(like MMM-Hotword).
For MMM-Hotword, you have to register voice models to use and just pronounce it. then it will do some command registered for that voice model.

**Comment by PiggiCZ** [comment]
Nonono, I was looking for the word to wake up the MagicMirror found out that the word is, Computer

**Comment by eouia** [comment]
```
models: [
{
hotwords : "computer",
file : "computer.umdl",
sensitivity : "0.5",
},
],
commands: {
"computer": {
notificationExec: {
notification: "ASSISTANT_ACTIVATE",
payload: (detected, afterRecord) => {
return {profile:"default"}
}
},
```
You've registered `computer` as hotword model and the command which would be activated by `computer`.

**Comment by PiggiCZ** [comment]
Thanks a lot, its working now..

I have another question:
Can you somehow make spotify to play from the RraspberryPi or is that not possible and you need to play it from Mobile or a PC and the MMM-spotify module is just for visual effect, so you can see whats playing now ?

**Comment by eouia** [comment]
MMM-Spotify itself could be used without RASPOTIFY.

**Comment by PiggiCZ** [comment]
this.sendNotification("SPOTIFY_SEARCH", {type:"artist,playlist", query:"michael+jackson", random:false})

Am I suppose to put these into config file to work ?

**Comment by PiggiCZ** [comment]
so the MMM-spotify works, but can you control it with voice ? through a mic ? or only by click on the mouse?

**Comment by eouia** [comment]
Maybe you can make a command using hotword to control MMM-Spotify.
