### ISSUE TITLE
The microphone doesn't work

### ISSUE THREAD

**Issue by aquasheep71** [eouia/MMM-Hotword#104]
We can discuss in Korean but now I cannot type Korean in Raspberry Pi :(  

I correctly installed MagicMirror with MMM-AssistantMk2 and MMM-Hotword. There is no error when I start the MagicMirror.

Only problem comes with the microphone. I'm using USB microphone and this is arecord -l results.
----------------------------------------------------------------------------------------
pi@raspberrypi:~/MagicMirror $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: Device [USB PnP Sound Device], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
----------------------------------------------------------------------------------------

and this is my config.js
----------------------------------------------------------------------------------------
 {
      module: "MMM-AssistantMk2",
      position: "top_right",
      config: {
        record: {
          recordProgram : "arecord",  
          device        : "plughw:1",
        },
        notifications: {
          ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
          ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
        },
        deviceLocation: {
          coordinates: {
            latitude: 37.57,
            longitude: 126.98
          }
        },
        profiles: {
          "default": {
           lang: "ko-KR"
          }
        }
      }
    },
    {
	module: "MMM-Hotword",
	position:"bottom_right",
      	config: {
      		chimeOnFinish: null,
	        mic: {
		  verbose:false,          
		  recordProgram : "arecord",  
	          device        : "plughw:1",		  
	        },
		models: [
		          {
		            hotwords: "smartmirror",
		            file: "SmartMirror.pmdl",
		            sensitivity: '0.8',
		          },
		          {
		            hotwords: "snowboy",
		            file: "snowboy.umdl",
		            sensitivity: '0.8',
		          },
		          {
		            hotwords: "HeyJavis",
			    file: "HeyJavis.pmdl",
		            sensitivity: '0.8',
		          },
			],
		commends: {
			"snowboy":{
				notificationsExec: {
					notification: "ASSISTANT_ACTIVATE",
					payload: (detected, afterRecord) => {
						return {profile:"default"}
						}
					},
					restart:false,
					afterRecordLimit:0
  				}
        		}
     		 }
    	},
----------------------------------------------------------------------------------------
The current setting is 
 device        : "plughw:1",	
but I also tried with
 device        : "plughw:1,0",	

I just tried "snowboy" for now. 

And this is what I got after starting the MagicMirror.
----------------------------------------------------------------------------------------
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Final Result: { detected: false }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
Whoops! There was an uncaught exception...
{ Error: spawn ENOMEM
    at ChildProcess.spawn (internal/child_process.js:357:11)
    at spawn (child_process.js:540:9)
    at LPCM16.start (/home/pi/MagicMirror/modules/MMM-Hotword/components/lpcm16.js:101:15)
    at Class.startListening (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:218:14)
    at Class.activate (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:176:10)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:72:16)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11)
    at Socket.emit (events.js:182:13)
    at /home/pi/MagicMirror/node_modules/socket.io/lib/socket.js:528:12
    at process._tickCallback (internal/process/next_tick.js:61:11) errno: 'ENOMEM', code: 'ENOMEM', syscall: 'spawn' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: MMM-AssistantMk2
Stopping module helper: MMM-Hotword
----------------------------------------------------------------------------------------

I also tried to set ./asoundrc following instruction 
https://github.com/makepluscode/rpi-tips/blob/master/001-bringup-audio-and-mic/.asoundrc

But it also didn't solve the problem.

How can I solve this problem? Please help.....

Q2. I have no clue why I have error after a few second starting the MagicMirror that displayed the log above. (starting with Whoops!)

**Comment by aquasheep71** [comment]
얘네는 왜 글씨크기가 이리 크게 됐는지;; 라즈베리파이에서 내용 복사하려고 글작성하다보니 한글이 안쳐져서 영어로 질문올립니다. 몇일동안 이문제로 고생중이라... 도움 주시면 감사하겠습니다 ㅜㅜ

**Comment by aquasheep71** [comment]
아.. 질문올리고 라즈베리파이 재시작을 한번해봤는데.. 마이크는 인식하는것 같네요! 그런데 여전히 구글어시스턴트가 작동하지느 않습니다.

로그에서는...

[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: snowboy
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'snowboy', file: null }
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: snowboy
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'snowboy', file: null }


이렇게 반복됩니다. 말을하고나면 아무런 반응이 없습니다.

MagicMirror/modules/MMM-Hotword/models 

경로안에 snowboy.umdl 파일은 존재하는데.. 파일이 null로 나와서 안잡힌건 무슨 문제인지요..?
(애초에 이경로에 파일이 없으면 매직미러 실행할때 에러가 떴던거같았는.. 에러는 안뜹니다.. )

**Comment by aquasheep71** [comment]
자문자답합니다.. config파일에서 command를 commend로 치는 오타 등 오타가 두건 있어서 호출 후에 구글 어시스턴트로 넘어가지 않았던거네요. 이제 잘 작동합니다! 이제 달력 추가하는걸..찾아봐야겠네요.
