### ISSUE TITLE
Don't recognize hotword

### ISSUE THREAD

**Issue by juanmam5** [eouia/MMM-Hotword#13]
Hello, with this new version I get my mirror working fine but I can't get it to recognize the hotword. Never. If I use the mouse to click over the icon, it get my voice perfectly and answers me, but when I say "Smart Mirror" or "Snowboy" it does nothing.

It seems to be no error while executing the application.

<img width="624" alt="captura de pantalla 2018-11-22 a las 10 42 49" src="https://user-images.githubusercontent.com/44181544/48894611-6e90c100-ee43-11e8-8e5f-5cea06e68540.png">

**Comment by eouia** [comment]
Well, when MMM-Hotword is started, `[HOTWORD] begins listening.` should be printed out in log. It happend?
Show me your configuration about MMM-Hotword

**Comment by juanmam5** [comment]
This is the configuration:
<img width="446" alt="captura de pantalla 2018-11-22 a las 11 28 47" src="https://user-images.githubusercontent.com/44181544/48897236-d0542980-ee49-11e8-83f6-96eabd239d3a.png">

And this is what I see in the command line. I don't know if you mean this when you say "should be printed out in log":
<img width="701" alt="captura de pantalla 2018-11-22 a las 11 31 34" src="https://user-images.githubusercontent.com/44181544/48897387-3ccf2880-ee4a-11e8-9e59-d7d18a7d01b8.png">

**Comment by juanmam5** [comment]
Also, this is my audio configuration in de .asoundrc file:
<img width="595" alt="captura de pantalla 2018-11-22 a las 11 03 16" src="https://user-images.githubusercontent.com/44181544/48897424-5bcdba80-ee4a-11e8-952f-eaa771a8f1e1.png">

**Comment by eouia** [comment]
Hmmm.. I don't know about asoundrc, so not sure. But, mic and speaker could have same hw name?
How did you setup `record` of MMM-AssistantMk2? MMM-Hotword use same format. Is it right your mic has the name `plughw:1` ? (asoundrc says `hw:0,1` but I cannot confirm this is right or not.)

**Comment by juanmam5** [comment]
I'll check it because right now I'm not with the mirror, but the thing is that MMM-AssistantMk2 is working fine. It get my voice and it answers correctly. For example if I ask "What time is it?", the mirror answers me with the hour perfectly and the voice is smooth and clear. It seems that the problem is in MMM-Hotword because it doesn't get the hotword and I have to use the mouse to click on the icon (top right) to speak to the mirror. Also, if I ask the mirror to play a YouTube video it doesn't sound, so maybe the sound configuration is not right either.

**Comment by juanmam5** [comment]
Ok I have checked my sound configuration. This is what I have:
i@raspberrypi:~ $ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Playback/recording through the PulseAudio sound server
mic
speaker
sysdefault:CARD=sndrpigooglevoi
    snd_rpi_googlevoicehat_soundcar, 
    Default Audio Device
dmix:CARD=sndrpigooglevoi,DEV=0
    snd_rpi_googlevoicehat_soundcar, 
    Direct sample mixing device
dsnoop:CARD=sndrpigooglevoi,DEV=0
    snd_rpi_googlevoicehat_soundcar, 
    Direct sample snooping device
hw:CARD=sndrpigooglevoi,DEV=0
    snd_rpi_googlevoicehat_soundcar, 
    Direct hardware device without any conversions
plughw:CARD=sndrpigooglevoi,DEV=0
    snd_rpi_googlevoicehat_soundcar, 
    Hardware device with all software conversions
-----------------------------------------------------------------------------------------------------------------------
pi@raspberrypi:~ $ arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
default
    Playback/recording through the PulseAudio sound server
mic
speaker
sysdefault:CARD=sndrpigooglevoi
    snd_rpi_googlevoicehat_soundcar, 
    Default Audio Device
dmix:CARD=sndrpigooglevoi,DEV=0
    snd_rpi_googlevoicehat_soundcar, 
    Direct sample mixing device
dsnoop:CARD=sndrpigooglevoi,DEV=0
    snd_rpi_googlevoicehat_soundcar, 
    Direct sample snooping device
hw:CARD=sndrpigooglevoi,DEV=0
    snd_rpi_googlevoicehat_soundcar, 
    Direct hardware device without any conversions
plughw:CARD=sndrpigooglevoi,DEV=0
    snd_rpi_googlevoicehat_soundcar, 
    Hardware device with all software conversions
------------------------------------------------------------------------------------------------------------
pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 0: sndrpigooglevoi [snd_rpi_googlevoicehat_soundcar], device 0: Google voiceHAT SoundCard HiFi voicehat-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
pi@raspberrypi:~ $ aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: sndrpigooglevoi [snd_rpi_googlevoicehat_soundcar], device 0: Google voiceHAT SoundCard HiFi voicehat-hifi-0 []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
---------------------------------------------------------------------------------------------------------------
I have changed asoundrc file to:
pcm.!default {
  type asym
  capture.pcm "mic"
  playback.pcm "speaker"
}
pcm.mic {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
pcm.speaker {
  type plug
  slave {
    pcm "hw:0,0"
  }
}
---------------------------------------------------------------------------------------------------------
But still there is no change. Hotword is still not recognizing "Smart Mirror"

Anything I could try?

**Comment by eouia** [comment]
In that case, your `record` configuration of MMM-AssistantMk2 & MMM-Hotword should be set as `hw:0,0`

**Comment by themcgamer1986** [comment]
it doesnt work for me either since the last update. i dont get the print that its listening anymore also. no reply in verbose mode when talking to the mirror as well

**Comment by themcgamer1986** [comment]
the config js  contains:

{
  module: "MMM-Hotword",
  config: {
    record: {
      recordProgram : "arecord",  
      device        : "null"
    },
    autostart:true,
    onDetected: {
      notification: (payload) => {
        return "ASSISTANT_ACTIVATE"
      },
      payload: (payload) => {
        return {
          profile: payload.hotword
        }
      }
    },
  },
},
{
    module: "MMM-AssistantMk2",
    position: "top_center",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "null",
      },

      notifications: {
        ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
        ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
      },
    }
  },

tried with the default hwplug did not work also hw 1,0  and my previous config for hotword and mk2 had null wich worked in the past.


-----------------------

pi@raspberrypi:~ $ arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: CameraB409241 [USB Camera-B4.09.24.1], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

-------------------------------
> magicmirror@2.5.0 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.5.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-Netatmo-Thermostat
Initializing new module helper ...
Module helper loaded: MMM-GAction
No helper found for module: compliments.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
Initializing new module helper ...
Module helper loaded: newsfeed
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: MMM-Netatmo-Thermostat
Starting module helper: MMM-Netatmo-Thermostat
Connecting socket for: MMM-GAction
Connecting socket for: MMM-Hotword
MMM-Hotword started
Connecting socket for: MMM-AssistantMk2
Connecting socket for: newsfeed
Starting module: newsfeed
Sockets connected & modules started ...
Whoops! There was an uncaught exception...
{ Error: listen EADDRINUSE 127.0.0.1:8080
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1501:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080 }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

**Comment by themcgamer1986** [comment]
both hotword and assistant mk2 are git pulled latest and configs are untouched

**Comment by eouia** [comment]
Well, the error of logs are not caused by module. It says you are running instances of MM multiply.

**Comment by themcgamer1986** [comment]
thats true i ran an extra session in terminal to get the verbose but even with the default auto start it wont work

**Comment by eouia** [comment]
But I need the exact the error log when it works abnormally. Without log I cannot see anything.

**Comment by eouia** [comment]
And one more thing;
Your `arecord -l` says, you have webcam and use it as mic(I guess). It says `plughw:1,0` is your mice device, but In your configuration, you have set `record:device` as `null`. Change it to `plughw:1,0` in both HOTWORD and ASSISTANTMK2 modules.

**Comment by themcgamer1986** [comment]
ok ive stopped the autoboot and got a log file.

it says hotword is listening but when saying the hotword the next appears:

Launching application.
INIT
[HOTWORD] begins listening.
{ Error: Cannot find module 'play-sound'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Class.play (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:24:20)
    at Class.playChime (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:42:10)
    at Class.prepareActivate (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:135:12)
    at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_helper.js:98:12)
    at Socket.<anonymous> (/home/pi/MagicMirror/modules/node_modules/node_helper/index.js:113:11) code: 'MODULE_NOT_FOUND' }
^C

**Comment by eouia** [comment]
You might have upgraded the newest MMM-AssistantMk2 from older than 2.1.0 (current version is 2.1.1)
Maybe you need fresh reinstall. or See https://github.com/eouia/MMM-AssistantMk2#old-updates
If your prior version was 2.0.0, `npm install --save play-sound` could be enough in MMM-AssistantMk2 directory.

**Comment by themcgamer1986** [comment]
im reinstalling the mk2 now ;)  took a while to reconfig but it works now
