### ISSUE TITLE
error when initiating module

### ISSUE THREAD

**Issue by nickbeaulieu98** [eouia/MMM-Hotword#16]
I'm getting this when Magic Mirror starts up:

Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues

**Comment by eouia** [comment]
https://github.com/eouia/MMM-Hotword/blob/master/README.md#installation
You’ve missed Electron-rebuilding.

**Comment by nickbeaulieu98** [comment]
I've done this and now I can initiate it by adding this into my config.js file, however it shows "MMM-Hotword" on the screen if I do that. How should I be initiating it properly? 

 {
			module: "MMM-Hotword",
			position: "top_right",
			
		},

**Comment by nickbeaulieu98** [comment]
I got it working, never mind :)
