### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by icripps** [eouia/MMM-Hotword#26]
hi, after adding the module for snowboy , when i 'npm start' the mirror the screen just becomes black and i cant even exit from it, i have to manually switch the program to the terminal and 'sudo reboot' before am able to access the desktop.

this is the module i added:
{
  module: "MMM-Hotword",
  config: {}
},

**Comment by eouia** [comment]
I need the error messages to examine. What is displayed on the terminal?(not MM). Without details I cannot tell you anything.

**Comment by icripps** [comment]
Starting MagicMirror: v2.6.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'node-record-lpcm16'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
App threw an error during load
Error: Cannot find module 'node-record-lpcm16'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:9:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:115:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module 'node-record-lpcm16'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:9:16)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:115:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.

@eouia

**Comment by eouia** [comment]
`Error: Cannot find module 'node-record-lpcm16'`
This mean you've failed to complete installation of dependencies.
Thea quick solution would be `npm install --save node-record-lpcm16`. But I doubt you've missed other things also. It would be better to reinstall. But choice is yours.

**Comment by eouia** [comment]
Have you solved this issue? There is no feedback any more, so I'll close this issue. I wish you a good luck.

**Comment by PabloOyarzo** [comment]
I'm having the same issue but don't know how to see the console with the errors

**Comment by eouia** [comment]
@PabloOyarzo If you are using `pm2`, just stop pm2 then execute MM with `npm start` on MM directory. you can see the log on your console.

**Comment by PabloOyarzo** [comment]
[31mWARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'[39m
App threw an error during load
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v2.0-linux-arm/snowboy.node'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32) code: 'MODULE_NOT_FOUND' }

**Comment by eouia** [comment]
You've missed or failed on `electron-rebuild` step of installation.

**Comment by PabloOyarzo** [comment]
Yep, sorry my bad. Did that, working great.
