### ISSUE TITLE
unable to install Hotword

### ISSUE THREAD

**Issue by next9812** [eouia/MMM-Hotword#37]
here is the output:

```
pi@raspberrypi:~/MMM-Hotword $ sudo npm install
npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/snowboy failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
npm WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).

> snowboy@1.3.1 install /home/pi/MMM-Hotword/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
gypgyp  WARNWARN  EACCESEACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.3"
 user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.3"
gypgyp  WARNWARN  EACCESEACCES attempting to reinstall using temporary dev dir "/home/pi/MMM-Hotword/node_modules/snowboy/.node-gyp"
 attempting to reinstall using temporary dev dir "/home/pi/MMM-Hotword/node_modules/snowboy/.node-gyp"
gyp WARN install got an error, rolling back install
gyp WARN install got an error, rolling back install
gypgyp  WARNWARN  installinstall got an error, rolling back install
 got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/MMM-Hotword/node_modules/snowboy/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
gyp ERR! cwd /home/pi/MMM-Hotword/node_modules/snowboy
gypgyp ERR!  node -v v10.15.3
ERR!gyp  ERR!configure error  
node-gyp -v v3.8.0
gypgyp  ERR! ERR!not ok  
stack Error: EACCES: permission denied, mkdir '/home/pi/MMM-Hotword/node_modules/snowboy/.node-gyp'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
gyp ERR! cwd /home/pi/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MMM-Hotword/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.14.98-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/MMM-Hotword/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/MMM-Hotword/node_modules/snowboy
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
npm WARN MMM-Hotword@1.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-16T14_35_13_951Z-debug.log
```

I also tried this:

```
pi@raspberrypi:~/MMM-Hotword $ cd ~/MagicMirror/modules/MMM-Hotword
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ sudo npm install --save snowboy
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm ERR! path /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm ERR! code EISGIT
npm ERR! git /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy: Appears to be a git repo or submodule.
npm ERR! git     /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-16T14_36_51_129Z-debug.log
```

**Comment by eouia** [comment]
first, it seems you were using inappropriate `sudo`. 
Half of errors become from abnormal permission because you used `sudo`. 

I recommend you to format your system and restart from scratch (Yes, it sounds horribly.) If you were using improper `sudo` to install MM or some other systems stuffs which are not instructed to use `sudo`, (even though not using `sudo` to this module), It would make various problems. I'm not sure you did or not, but if you did, it will be a hell of errors.

If you have a confidence of not using `sudo` on other previous things, just try `npm install` again. It might show some errors or not, anyway, we can talk from there.

**Comment by next9812** [comment]
thanks for quick reply, I re-installed the system and magic mirror, here is what I get now:
```
pi@raspberrypi:~/MMM-Hotword $ npm install
npm WARN deprecated hawk@3.1.3: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This version has been deprecated. Please upgrade to the latest version to get the best features, bug fixes, and security patches.

> snowboy@1.3.1 install /home/pi/MMM-Hotword/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.15.3 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:119:20)
    at Object.runInThisContext (vm.js:326:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at evalScript (internal/bootstrap/node.js:589:27)
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'nan'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:119:20)
    at Object.runInThisContext (vm.js:326:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at evalScript (internal/bootstrap/node.js:589:27)
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gypgyp  ERR!ERR!  configure errorconfigure error 
 
gypgyp  ERR! ERR!stack  Error: `gyp` failed with exit code: 1
stackgyp  Error: `gyp` failed with exit code: 1
ERR! gypstack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
 gypERR!  ERR! stackstack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
     at ChildProcess.emit (events.js:189:13)
gypgyp  ERR! ERR!stack      at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! gypstack      at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
ERR! System Linux 4.14.98-v7+
gypgyp ERR!  commandERR! "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
 System Linux 4.14.98-v7+
gyp ERR! cwd /home/pi/MMM-Hotword/node_modules/snowboy
gyp gypERR!  node -v v10.15.3
ERR! gyp commandERR! "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
 node-gyp -v v3.8.0
gypgyp  ERR! ERR!not ok 
 cwd /home/pi/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MMM-Hotword/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.14.98-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/MMM-Hotword/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/MMM-Hotword/node_modules/snowboy
node-pre-gyp ERR! node -v v10.15.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
npm WARN MMM-Hotword@1.1.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! snowboy@1.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the snowboy@1.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-04-16T18_14_51_133Z-debug.log
```

**Comment by eouia** [comment]
```
cd ~/MagicMirror/modules/MMM-Hotword/node_modules
rm -rf snowboy
git clone https://github.com/Kitt-AI/snowboy.git
cd snowboy
rm -rf .git
npm install --save node-pre-gyp@0.12.0
npm install nan
npm install
```
Many errors or warnings could be happen, but just check these after above processes.

1)
```
ls lib/node
```
There should be `index.js` and `index.ts`

2)
```
ls lib/node/binding/Release
```
There should be `node-VXX-linux-arm` folder (name could be slightly different)

If not, show me error logs of installation.

Wish a good luck.

**Comment by next9812** [comment]
```
pi@raspberrypi:~/MMM-Hotword $ cd ~/MagicMirror/modules/MMM-Hotword/node_modules
bash: cd: /home/pi/MagicMirror/modules/MMM-Hotword/node_modules: No such file or directory
```

**Comment by eouia** [comment]
OK.
```
cd ~/MagicMirror/modules/MMM-Hotword
npm install --save nan
npm install --save node-record-lpcm16
git clone https://github.com/Kitt-AI/snowboy.git
cd snowboy
# follow previous instruction from `cd snowboy`...
```

**Comment by next9812** [comment]
I only got "default","node modules" and "README.md" inside ~/MagicMirror/modules
am i missed some steps?

**Comment by next9812** [comment]
I am now having a new problem, I added 
```
{
  module: "MMM-Hotword",
  config: {}
},
```
to MM's config, and all I get is black screen, here is the log:
```
pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v3.0-linux-arm/snowboy.node'
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
App threw an error during load
Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v3.0-linux-arm/snowboy.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module '/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/electron-v3.0-linux-arm/snowboy.node'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:8:29)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/index.js:141:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
```

**Comment by eouia** [comment]
You didn't do `electron-rebuild` step to use on Electron (frontend of MM). Read the instruction. https://github.com/eouia/MMM-Hotword#installation

**Comment by next9812** [comment]
It's working great now, thanks

**Comment by eouia** [comment]
Nice to hear it. I'll close this.
