### ISSUE TITLE
Can't find module snowboy

### ISSUE THREAD

**Issue by YangDaewon** [eouia/MMM-Hotword#53]
When I started the magic mirror, 
There are already ./snowboy/lib/node/index.js, but they say they can't find the module. Can you give me a solution?

pi@raspberrypi:~/MagicMirror $ npm start

> magicmirror@2.7.1 start /home/pi/MagicMirror
> sh run-start.sh

Starting MagicMirror: v2.7.1
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-NotificationTrigger
WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module './snowboy/lib/node/index.js'
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
Initializing new module helper ...
Module helper loaded: calendar
Initializing new module helper ...
Module helper loaded: MMM-NotificationTrigger
App threw an error during load
Error: Cannot find module './snowboy/lib/node/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:234:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
Whoops! There was an uncaught exception...
{ Error: Cannot find module './snowboy/lib/node/index.js'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_helper.js:234:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
MagicMirror will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
If you think this really is an issue, please open an issue on GitHub: https://github.com/MichMich/MagicMirror/issues
Launching application.
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: MMM-NotificationTrigger
Stopping module helper: updatenotification
Stopping module helper: calendar
Stopping module helper: MMM-NotificationTrigger

**Comment by eouia** [comment]
한국분이시죠? NotificationTrigger가 설치되어 있는 걸 보니 어디에선가 돌고 있는 옛날 버전 설치법을 따르고 계신 것 같아요.  새버전은 많이 다르니 github의 문서를 직접 보시고 적힌 대로 새로 설치해주세요
