### ISSUE TITLE
Conversation Error After 3-4 Successful Hotword Commands 

### ISSUE THREAD

**Issue by dresch27** [eouia/MMM-Hotword#64]
Thank you for building an amazing module! Not sure why, but after 3-4 successful commands using the hotword, I get a "Conversation_Error" message. Any help would be greatly appreciated. 

Using the latest Raspbian Stretch

Here is my config for the module:

 {
    module: "MMM-Hotword",
   position: "top_right",
    config: {
      record: {
        recordProgram : "arecord",  
        device        : "plughw:1,0",
	
      },
      autostart: true,
	autorestart: true,
 onDetected: {
        notification: function (payload) {
          return "ASSISTANT_ACTIVATE"
        },
        payload: function (payload){
          return {
            profile: payload.hotword
          }

        }
      },
    },
  },

Here is the error - after a few successful hotword commands, it crashes and freezes after "[HOTWORD] begins listening" below:

[AMK2] Conversation Error: { Error: 3 INVALID_ARGUMENT: Invalid 'audio_in': audio frame length is too long.
    at Object.exports.createStatusError (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/common.js:91:15)
    at ClientDuplexStream._emitStatusIfDone (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:233:26)
    at ClientDuplexStream._receiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client.js:211:8)
    at Object.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1306:15)
    at InterceptingListener._callNext (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:618:8)
    at /home/pi/MagicMirror/modules/MMM-AssistantMk2/node_modules/grpc/src/client_interceptors.js:1123:18
  code: 3,
  metadata:
   Metadata { _internal_repr: { 'content-disposition': [Array] } },
  details: 'Invalid \'audio_in\': audio frame length is too long.' }
[HOTWORD] begins listening.

**Comment by eouia** [comment]
sorry for late answer. I was on vacation.
Anyway, You seems using old version, it might be the reason.

**Comment by dresch27** [comment]
Thank you very much for your reply.

It is the latest upgraded 2.0 version of MMM-Hotword. I'm wondering if it could be that the delay or some other setting is not set properly? Just guessing. 

Thanks again

**Comment by eouia** [comment]
You might have installed latest version, but your configuration seems still ver1.x (I've deprecated `onDetected` on ver 2)
