### ISSUE TITLE
Problem install

### ISSUE THREAD

**Issue by ayos-fr** [eouia/MMM-Hotword#99]
Hi i have a problem with the installation of MMM-Hotword.
I want to use for magicmirror. 

```
cd ~/MagicMirror/modules/
git clone https://github.com/eouia/MMM-Hotword.git
cd MMM-Hotword
npm install
```
first problem with npm install

`npm notice created a lockfile as package-lock.json. You should commit this file.
`
i do this 

```
npm install nan
npm install
```

no error but no snowboy folder on MMM-Hotword/node_modules/   just nan folder, so i do this on MMM_Hotword folder

```
git pull
npm install --save snowboy 
```
this error : 
```
> snowboy@1.3.1 install /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.15.2 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.15.2 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.75-v7l+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/bin/node-gyp build --fallback-to-build --module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node --module_name=snowboy --module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 4.19.75-v7l+
node-pre-gyp ERR! command "/usr/bin/node" "/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
node-pre-gyp ERR! node -v v10.15.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.39
node-pre-gyp ERR! not ok 

```

so i do this : 
```
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword $ cd ~/MagicMirror/modules/MMM-Hotword/node_modules
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules $ rm -rf snowboy
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules $ git clone https://github.com/Kitt-AI/snowboy.git
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules $ cd snowboy
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy $ npm install nan
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy $ npm install

```

this error : 

```
node-pre-gyp ERR! Tried to download(403): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.15.2 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp ERR! Tried to download(undefined): https://snowboy-release-node.s3-us-west-2.amazonaws.com/snowboy/v1.3.1/Release/snowboy-v1.3.1-node-v64-linux-arm.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for snowboy@1.3.1 and node@10.15.2 (node-v64 ABI, glibc) (falling back to source compile with node-gyp) 
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.19.75-v7l+
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "build" "--fallback-to-build" "--module=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm/snowboy.node" "--module_name=snowboy" "--module_path=/home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy/lib/node/binding/Release/node-v64-linux-arm"
gyp ERR! cwd /home/pi/MagicMirror/modules/MMM-Hotword/node_modules/snowboy
gyp ERR! node -v v10.15.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

```
`
pi@raspberrypi:~/MagicMirror/modules/MMM-Hotword/node_modules/snowboy $ npm install`

```
> tsc --listFiles

../../../../node_modules/@types/unist/index.d.ts:31:20 - error TS2304: Cannot find name 'unknown'.

31     [key: string]: unknown;
                      ~~~~~~~


../../../../node_modules/@types/unist/index.d.ts:40:20 - error TS2304: Cannot find name 'unknown'.

40     [key: string]: unknown;
                      ~~~~~~~


../../../../node_modules/@types/unist/index.d.ts:97:12 - error TS2304: Cannot find name 'unknown'.

97     value: unknown;
              ~~~~~~~


../../../../node_modules/@types/vfile/index.d.ts:48:15 - error TS2304: Cannot find name 'unknown'.

48         data: unknown;
                 ~~~~~~~


../../../../node_modules/vfile-message/types/index.d.ts:67:20 - error TS2304: Cannot find name 'unknown'.

67     [key: string]: unknown
                      ~~~~~~~

```

So snowboy don't work.

Anyone have an idea ?

**Comment by eouia** [comment]
?? It looks so old version.
I provide auto installer. Have you followed the instruction https://github.com/eouia/MMM-Hotword/blob/master/documents/install.md ?

**Comment by ayos-fr** [comment]
arff i'm suck

I follow your link and its ok.  Mirrormagic launch, but i have a probleme with the assistant google. I have the logo on mirrormagic, he speech the the "briefday" without problem, but i don't answer when i say "jarvis" or "magicmirror". if i click to the logo its work. I am depressed

**Comment by eouia** [comment]
If you confirmed the installation with `useWelcomeMessage`, just remove it and try again.

**Comment by ayos-fr** [comment]
i think it's my config.js the problem : 


```
{
  module: "MMM-Hotword",
  position: "top_left",
  config: {
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:1"
    },
    models: [
      {
        hotwords    : "jarvis",
        file        : "jarvis.umdl",
        sensitivity : "0.5",
      },
    ],
    commands: {
      "computer": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: (detected, afterRecord) => {
            return {profile:"default"}
          }
        },
        restart:false,
        afterRecordLimit:0
      }
    }
  }
},
		{
			module: "MMM-AssistantMk2",
			position: "top_left",
			config: {
				screenDuration: 5000, //this is milliseconds
				deviceLocation: {
					coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
					latitude: 48.0785146, // -90.0 - +90.0 laval 48.0785146
					longitude: -0.7669906, // -180.0 - +180.0  -0.7669906
					},
				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
	
				profiles: {
					"default" : {
						lang: "fr-FR"
					}
				},
			}
		},
```

**Comment by eouia** [comment]
Still have you problem?

**Comment by ayos-fr** [comment]
yes I have beautiful shout "jarvis" "smart mirror" "ok google"; he does not react. But if I click it works

**Comment by eouia** [comment]
Your configuration shows you only registered `jarvis` as hotword, so other hotwords will not work.

For Jarvis, your setting was wrong.
Read the docs; https://github.com/eouia/MMM-Hotword/blob/master/documents/models.md

**Comment by ayos-fr** [comment]
it must be that : 
```
		{
  module: "MMM-Hotword",
  position: "top_left",
  config: {
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:1"
    },
    models: [
      {
        hotwords    : ["jarvis", "jarvis"],
        file        : "jarvis.umdl",
        sensitivity : "0.8,0.8",
      },
    ],
    commands: {
      "computer": {
        notificationExec: {
          notification: "ASSISTANT_ACTIVATE",
          payload: (detected, afterRecord) => {
            return {profile:"default"}
          }
        },
        restart:false,
        afterRecordLimit:0
      }
    }
  }
},
```

**Comment by eouia** [comment]
Ignore those sentences. You are using `umdl`(`jarvis.umdl`), so not related with your case.

**Comment by ayos-fr** [comment]
it still does not work

perhaps a probleme with AssistantMk2, 
on the screen i have this : 

```
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
starting network connection testing
[HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }

```
so he detects me but does nothing after. That's right ?

**Comment by eouia** [comment]
Hotword looks working. 
So, How about AMK2 related logs? is there no log about it?

**Comment by ayos-fr** [comment]
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.

**Comment by eouia** [comment]
That's all? show the whole log. interaction and order are important to inspect details.

**Comment by ayos-fr** [comment]
```
Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
No helper found for module: alert.
Initializing new module helper ...
Module helper loaded: updatenotification
No helper found for module: clock.
No helper found for module: currentweather.
No helper found for module: weatherforecast.
Initializing new module helper ...
Module helper loaded: newsfeed
Initializing new module helper ...
Module helper loaded: MMM-NetworkConnection
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: updatenotification
Connecting socket for: newsfeed
Starting module: newsfeed
Connecting socket for: MMM-NetworkConnection
MMM-NetworkConnection helper started ...
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
Create new news fetcher for url: https://www.francetvinfo.fr/titres.rss - Interval: 300000
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
starting network connection testing
[HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: newsfeed
Stopping module helper: MMM-NetworkConnection
Stopping module helper: MMM-Hotword
Stopping module helper: MMM-AssistantMk2
```

**Comment by eouia** [comment]
I found what's wrong.
```js
 commands: {
      "computer": {
        notificationExec: {
```

You registered hotword model "jarvis", but the command of what to do was defined for only `computer`. Change it to `jarvis`

**Comment by ayos-fr** [comment]
always the same, and i must tel 6 or 7 time Jarvis for the logo of Hotword change

**Comment by eouia** [comment]
Will not the same, If your configuration would be right.

And, .umdl is a universal model, so it will fit common vocal pattern of most people, but it means it could not be fitted perfectly with a specific person. In that case, make your own personal model (.pmdl)

Anyway, before trying to create your .pmdl, adjust your mic volume and sensitivity. In most case, too low mic volume would be the issue.

**Comment by ayos-fr** [comment]
```
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
starting network connection testing
[HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
Shutting down server...
Stopping module helper: updatenotification
Stopping module helper: newsfeed
Stopping module helper: MMM-NetworkConnection
Stopping module helper: MMM-Hotword
Stopping module helper: MMM-AssistantMk2
```
after changing computer for jarvis

**Comment by eouia** [comment]
Can you test one more? but other modules should be commented out from the configuration. Leave only MMM-Hotword and MMM-AssistantMk2.

**Comment by ayos-fr** [comment]
the same : 

```
Starting MagicMirror: v2.9.0
Loading config ...
Loading module helpers ...
Initializing new module helper ...
Module helper loaded: MMM-Hotword
Initializing new module helper ...
Module helper loaded: MMM-AssistantMk2
All module helpers loaded.
Starting server on port 8080 ... 
Server started ...
Connecting socket for: MMM-Hotword
[HOTWORD] MMM-Hotword starts
Connecting socket for: MMM-AssistantMk2
Sockets connected & modules started ...
Launching application.
[AMK2] Recipe is loaded: hide_and_show_all_modules.js
[AMK2] Recipe is loaded: reboot.js
[AMK2] Recipe is loaded: screen_onoff.js
[AMK2] Recipe is loaded: shutdown.js
[AMK2] Temporal storage directory is clearing.
[HOTWORD] begins.
[HOTWORD] Detector starts listening.
[HOTWORD] Detected: jarvis
[HOTWORD] stops.
[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
Shutting down server...
Stopping module helper: MMM-Hotword
Stopping module helper: MMM-AssistantMk2
```

my config.js : 
```
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "fr",
	timeFormat: 24,
	units: "metric",

	modules: [
		
	
		{
  module: "MMM-Hotword",
  position: "top_left",
  config: {
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:1"
    },
    models: [
      {
        hotwords    : ["jarvis", "jarvis"],
        file        : "jarvis.umdl",
        sensitivity : "1,1",
      },
    ],
    commands: 	{
      		"jarvis":	{
        			notificationExec: 	{
          						notification: "ASSISTANT_ACTIVATE",
         						 payload: (detected, afterRecord) => {
            						return {profile:"default"}
          											}
      							  },
      				  restart:false,
       				 afterRecordLimit:0
      				}
   		 }
  }
},
		{
			module: "MMM-AssistantMk2",
			position: "top_left",
			config: {
				screenDuration: 5000, //this is milliseconds
				deviceLocation: {
					coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
					latitude: 48.0785146, // -90.0 - +90.0 laval 48.0785146
					longitude: -0.7669906, // -180.0 - +180.0  -0.7669906
					},
				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
	
				profiles: {
					"default" : {
						lang: "fr-FR"
					}
				},
			}
		},


]





};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}

```

it's strange normaly when hotword listen "jarvis" he must send a notification ASSISTANT_ACTIVATE and assistantmk2 receive this ASSISTANT ACTIVATE, it's right ?

**Comment by eouia** [comment]
> it's strange normaly when hotword listen "jarvis" he must send a notification ASSISTANT_ACTIVATE and assistantmk2 receive this ASSISTANT ACTIVATE, it's right ?

Right. After `[HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }` AMK2 should be activated. but not. Hmmmm. 
If you are execution MM with `npm start dev`, you can see front-end dev-console. In that console, any suspicious error exists?

**Comment by ayos-fr** [comment]
i put the log dev-console  : 

```
main.js:454 Initializing MagicMirror.
translator.js:202 Loading core translation file: translations/fr.json
translator.js:225 Loading core translation fallback file: translations/en.json
loader.js:179 Load script: modules/MMM-Hotword//MMM-Hotword.js
module.js:476 Module registered: MMM-Hotword
loader.js:150 Bootstrapping module: MMM-Hotword
loader.js:179 Load script: https://code.iconify.design/1/1.0.2/iconify.min.js
loader.js:155 Scripts loaded for: MMM-Hotword
loader.js:194 Load stylesheet: modules/MMM-Hotword/MMM-Hotword.css
loader.js:157 Styles loaded for: MMM-Hotword
loader.js:159 Translations loaded for: MMM-Hotword
loader.js:179 Load script: modules/MMM-AssistantMk2//MMM-AssistantMk2.js
module.js:476 Module registered: MMM-AssistantMk2
loader.js:150 Bootstrapping module: MMM-AssistantMk2
loader.js:179 Load script: modules/MMM-AssistantMk2/vendor/serialize.js
loader.js:155 Scripts loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: modules/MMM-AssistantMk2/MMM-AssistantMk2.css
loader.js:157 Styles loaded for: MMM-AssistantMk2
loader.js:159 Translations loaded for: MMM-AssistantMk2
loader.js:194 Load stylesheet: css/custom.css
main.js:472 All modules started!
null:1 Failed to load resource: the server responded with a status of 404 (Not Found)
MMM-AssistantMk2.js:333 [AMK2]  YouTube iframe API is ready.
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127 Electron Security Warning (Insecure Resources) This renderer process loads resources using insecure
    protocols.This exposes users of this app to unnecessary security risks.
    Consider loading the following resources over HTTPS or FTPS. 
 - http://localhost:8080/css/main.css
- http://localhost:8080/fonts/roboto.css
- http://localhost:8080/socket.io/socket.io.js
- http://localhost:8080/vendor/node_modules/nunjucks/browser/nunjucks.min.js
- http://localhost:8080/js/defaults.js
- http://localhost:8080/config/config.js
- http://localhost:8080/vendor/vendor.js
- http://localhost:8080/modules/default/defaultmodules.js
- http://localhost:8080/js/logger.js
- http://localhost:8080/translations/translations.js
- http://localhost:8080/js/translator.js
- http://localhost:8080/js/class.js
- http://localhost:8080/js/module.js
- http://localhost:8080/js/loader.js
- http://localhost:8080/js/socketclient.js
- http://localhost:8080/js/main.js
- http://localhost:8080/fonts/node_modules/roboto-fontface/fonts/roboto-condensed/Roboto-Condensed-Regular.woff2
- http://localhost:8080/translations/fr.json
- http://localhost:8080/translations/en.json
- http://localhost:8080/modules/MMM-Hotword//MMM-Hotword.js
- http://localhost:8080/modules/MMM-Hotword/MMM-Hotword.css
- http://localhost:8080/modules/MMM-AssistantMk2//MMM-AssistantMk2.js
- http://localhost:8080/modules/MMM-AssistantMk2/vendor/serialize.js
- http://localhost:8080/modules/MMM-AssistantMk2/MMM-AssistantMk2.css
- http://localhost:8080/css/custom.css
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MxMcs_K
- http://localhost:8080/modules/MMM-AssistantMk2/resources/assistant.png
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MxMct0g&sid=f0JrcsykpK8Bns6BAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MxMct0r&sid=f0JrcsykpK8Bns6BAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MxMct1l&sid=f0JrcsykpK8Bns6BAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MxMct1p&sid=f0JrcsykpK8Bns6BAAAA
- http://localhost:8080/socket.io/?EIO=3&transport=polling&t=MxMct2U&sid=f0JrcsykpK8Bns6BAAAA
    
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureResources @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:127
/home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
      Policy set or a policy with "unsafe-eval" enabled. This exposes users of
      this app to unnecessary security risks.
 
For more information and help, consult
https://electronjs.org/docs/tutorial/security.
 This warning will not show up
once the app is packaged.
warnAboutInsecureCSP @ /home/pi/MagicMirror/node_modules/electron/dist/resources/electron.asar/renderer/security-warnings.js:184

```

**Comment by eouia** [comment]
Very weird. Nothing seems suspicious to prevent working. hmmm....

**Comment by ayos-fr** [comment]
Yes and when i clic in amk2 logo the assistant work very well.  
Where i can see the notification who activate amk2 ?

**Comment by eouia** [comment]
https://github.com/eouia/MMM-AssistantMk2/blob/45423f492d10bb1a02972adf1e01eb3f0a1e894d/MMM-AssistantMk2.js#L175-L176
```
  notificationReceived: function (notification, payload, sender) {
    console.log(">>", notification, payload) // Add this line.
    switch(notification) {
```
You can see all notifications from external modules.

**Comment by ayos-fr** [comment]
how to check if it is hotword not launching the notification or if it is amk2 not listenning ?

**Comment by eouia** [comment]
Use that code of above post. If it is working, you can see all the notification received on AMK2. if there is no `ASSISTANT_ACTIVATE`, that notification is not emitted.

**Comment by ayos-fr** [comment]
where i put the code ?? in config.js ?

**Comment by eouia** [comment]
I gave you already link. `MMM-AssistantMk2.js`.

**Comment by ayos-fr** [comment]
i put the line
 console.log(">>", notification, payload) // Add this line.

but when i restart nothing on console 

can we do the same when hotword must send the notification ?

**Comment by eouia** [comment]
```
{
  notification: "ASSISTANT_ACTIVATE",
  payload: (detected, afterRecord) => {
    console.log("ASSISTANT_ACTIVATE notification emitting")
    return {profile:"default"}
  }
},
```

**Comment by ayos-fr** [comment]
always the same : 

```
> [AMK2] Recipe is loaded: hide_and_show_all_modules.js
> [AMK2] Recipe is loaded: reboot.js
> [AMK2] Recipe is loaded: screen_onoff.js
> [AMK2] Recipe is loaded: shutdown.js
> [AMK2] Temporal storage directory is clearing.
> [HOTWORD] begins.
> [HOTWORD] Detector starts listening.
> [HOTWORD] Detected: jarvis
> [HOTWORD] stops.
> [HOTWORD] Final Result: { detected: true, hotword: 'jarvis', file: null }
> Shutting down server...
> Stopping module helper: MMM-Hotword
> Stopping module helper: MMM-AssistantMk2
> 
```

its my config .js sure : 

```
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */




var config = {
	address: "localhost", // Address to listen on, can be:
	                      // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
	                      // - another specific IPv4/6 to listen on a specific interface
	                      // - "", "0.0.0.0", "::" to listen on any interface
	                      // Default, when address config is left out, is "localhost"
	port: 8080,
	ipWhitelist: ["127.0.0.1", "::ffff:127.0.0.1", "::1"], // Set [] to allow all IP addresses
	                                                       // or add a specific IPv4 of 192.168.1.5 :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
	                                                       // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
	                                                       // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	language: "fr",
	timeFormat: 24,
	units: "metric",

	modules: [
		
	
		{
  module: "MMM-Hotword",
  position: "top_left",
  config: {
    chimeOnFinish: null,
    mic: {
      recordProgram: "arecord",
      device: "plughw:1"
    },
    models: [
      {
        hotwords    : ["jarvis", "jarvis"],
        file        : "jarvis.umdl",
        sensitivity : "1,1",
      },
    ],
    commands: 	{
      		"jarvis":	{
				
        			notificationExec: 	{

          						notification: "ASSISTANT_ACTIVATE",
         						 payload: (detected, afterRecord) => {
							console.log("ASSISTANT_ACTIVATE notification emitting")            						
							return {profile:"default"}
          											}
      							  },
      				  restart:false,

       				 afterRecordLimit:0
      				}
   		 }
  }
},
		{
			module: "MMM-AssistantMk2",
			position: "top_left",
			config: {
				screenDuration: 5000, //this is milliseconds
				deviceLocation: {
					coordinates: { // set the latitude and longitude of the device to get localized information like weather or time. (ref. mygeoposition.com)
					latitude: 48.0785146, // -90.0 - +90.0 laval 48.0785146
					longitude: -0.7669906, // -180.0 - +180.0  -0.7669906
					},
				},
				record: {
					recordProgram : "arecord",  
					device        : "plughw:1",
				},
				notifications: {
					ASSISTANT_ACTIVATED: "HOTWORD_PAUSE",
					ASSISTANT_DEACTIVATED: "HOTWORD_RESUME",
				},
	
				profiles: {
					"default" : {
						lang: "fr-FR"
					}
				},
			}
		},


]





};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
****
```

**Comment by ProfKP** [comment]
I have a similar issue so watching this thread

**Comment by eouia** [comment]
I've updated it to `2.0.2`. It has some more front-end logs about command working.

**Comment by ayos-fr** [comment]
i've update hotword with this  : 
```

cd ~/MagicMirror/modules
git clone https://github.com/eouia/MMM-Hotword.git
cd MMM-Hotword

chmod +x ./installer/install.sh
./installer/install.sh
```

and now it's works perfectly
